Revert "u-boot-imx: Align with upstream"
The upstream change does not work well with the stmm implementation and
causes an imx-boot build failure:
```
| NOTE: building iMX8MP - TEE=tee.bin-stmm flash_evk_stmm_capsule
| dtc -@ -I dts -O dtb -o signature.dtbo signature.dts
| fdtoverlay -i imx8mp-evk.dtb -o imx8mp-evk.dtb signature.dtbo
| Couldn't open blob from 'imx8mp-evk.dtb': No such file or directory
|
| Failed to read 'imx8mp-evk.dtb'
| make[1]: *** [soc.mak:268: overlay] Error 1
| make: *** [Makefile:26: flash_evk_stmm_capsule] Error 2
| WARNING: exit code 2 from a shell command.
NOTE: recipe imx-boot-1.0-r0: task do_compile: Failed
ERROR: Task (meta-imx/meta-imx-bsp/recipes-bsp/imx-mkimage/imx-boot_1.0.bb:do_compile) failed with exit code '1'
```

Revert for now.

This reverts commit dde804950622f813bfb28a68e8a786c73008634d.